return PlaceObj('ModDef', {
	'title', "Coloured Depots",
	'description', "Compatible with Cernan update (Space Race & Green Planet DLCs)\n\nChanges the default yellow colour of the depots to match the colours presented in the standard info bar. Option exists to use the skin/paintbrush system to swap back to mono if wanted.\n\nThe automated depots may remain texture-less unless a small depot of that type has been built before hand. (This issue should now be fixed, but easy solution if it does crop up)\n\nIncludes support for LukeH's excellent extra Resources Mod;\nhttps://steamcommunity.com/sharedfiles/filedetails/?id=1742141295\n\nSee also my companion mod for Extended Depots;\nhttps://steamcommunity.com/sharedfiles/filedetails/?id=1793460653\n\nSpecial Thanks to :\nChoGGi for various code fixes and tweaks\nEaglescout93 Modding Support\nLukeH for asking me to update with support for his mod\n\nUpdate Notes; If you had built Hydrocarbon Depots prior to v8 they might show as a spinning white cube on Game Load, they should be safe to Salvage/remove.",
	'image', "Thumbnail.PNG",
	'last_changes', "v9.1 Cut/copy/paste error accidently gave meat storage the visuals of booze storage",
	'ignore_files', {
		"*.git/*",
		"*.svn/*",
		"*Preview*",
	},
	'id', "wezcHcZ",
	'steam_id', "1575253675",
	'pops_desktop_uuid', "a5995007-a5b0-48de-8645-9dd81cb8795c",
	'pops_any_uuid', "48b717f0-d288-493f-957c-f6e6c168bb07",
	'author', "RustyDios",
	'version_major', 1,
	'version_minor', 1,
	'version', 49,
	'lua_revision', 233360,
	'saved_with_revision', 249143,
	'code', {
		"Code/Script.lua",
	},
	'saved', 1585201469,
	'screenshot1', "Preview.PNG",
	'screenshot2', "Preview1.PNG",
	'screenshot3', "Preview2.PNG",
	'screenshot4', "Preview3.jpg",
	'TagBuildings', true,
	'TagCosmetics', true,
	'TagOther', true,
})